using UnityEngine;
using UnityEngine.UI;
public class Reverse : MonoBehaviour
{
    public Image topImage;      // ã”¼•ª‚ÌImage

    private bool isDefault = true; // Œ»İ‚Ìó‘Ô‚ğ‹L˜^itrue=ã”’‰º•j

    void Start()
    {
        // ‰Šúó‘Ô‚ğİ’è
        SetDefaultColors();
    }
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space)) // ‰Ÿ‚µ‚½uŠÔ‚¾‚¯”½‰
        {
            if (isDefault)
            {
                SetAlternateColors(); // ”½“]ó‘Ô‚É‚·‚é
            }
            else
            {
                SetDefaultColors(); // Œ³‚É–ß‚·
            }
            isDefault = !isDefault; // ó‘Ô‚ğØ‚è‘Ö‚¦
        }
    }
    private void SetDefaultColors()
    {
        topImage.color = Color.white;
       
    }
    private void SetAlternateColors()
    {
        topImage.color = Color.black;
        
    }
}
